name: 'earthquake_project'
version: '1.0.0'
config-version: 2
profile: 'earthquake_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  earthquake_project:
    staging:
      +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: table
