earthquake_project:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: 5432
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'earthquakes') }}"
      schema: public
  target: dev
